server:
  port: 8084

spring:
  application:
    name: ecommerce-backend
  data:
    rest:
      base-path: /api/v1

  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
